### ISSUE TITLE
Host the website [IMPROVEMENT]

### ISSUE THREAD

**Issue by laxyapahuja** [Practikality/Healr#1]
@padamchopra host the website when you get the time so that it's easy to access.

**Comment by padamchopra** [comment]
It's already up and running [here](https://practikality.github.io/Healr/). The website address is also mentioned at the beginning of the [code tab](https://github.com/Practikality/Healr).

Kindly cross-check before creating issues. 
Cheers.

**Comment by laxyapahuja** [comment]
holy shit, how did I not notice that lol.
oops sorry
